# Basic 
type: DT4D
dataset_path: /mnt/hdd/motion_animal
mode: diff
stage: deform
repeat: 1 # enlarge the dataset by repeating the data, 1 -> no repeat
pc_size: 2048 # surface sampling
num_samples: 1024 # vol + near for each
seed: 0

# Input setting
n_inputs: 512
inputs_noise_std: 0.001
use_half: False
use_depth: False

length_sequence: 17
offset_sequence: 0
n_training_frames: 5

time_attn: True
is_corr: True

shape_ae_model: kl_d512_m512_l8
shape_ae_model_path: ./ckpts/DT4D/dt4d_shape_ae.pth

deform_ae_model: kl_d512_m512_l32
deform_ae_model_path: ./ckpts/DT4D/dt4d_deform_ae.pth

diff_model: surf512_edm

# Training
batch_size: 4 # It's max for 24GB GPU
lr: 0.0001
epochs: 50
warmup_epochs: 0
accum_iter: 2 
save_every: 10
eval_every: 10

# From which (if you want to resume or load ckpt)
resume: False